from typing import Protocol, Optional, Any, List


class CachePort(Protocol):
    async def get(self, key: str) -> Optional[Any]: ...
    async def set(self, key: str, value: Any, ttl: Optional[int] = None) -> bool: ...
    async def delete(self, key: str) -> bool: ...
    async def exists(self, key: str) -> bool: ...
    async def clear(self) -> int: ...
    async def keys(self, pattern: str = "*") -> List[str]: ...
