from typing import Protocol, Optional, List
from boxlite.models import CommandResult, FileEntry, SandboxState


class SandboxPort(Protocol):
    async def initialize(self, reset: bool = False) -> SandboxState: ...
    async def cleanup(self) -> None: ...
    async def write_file(self, path: str, content: str) -> bool: ...
    async def read_file(self, path: str) -> Optional[str]: ...
    async def delete_file(self, path: str) -> bool: ...
    async def list_files(self, path: str = "/") -> List[FileEntry]: ...
    async def run_command(
        self,
        command: str,
        args: Optional[List[str]] = None,
        timeout: float = 60.0,
        background: bool = False,
    ) -> CommandResult: ...
    async def start_dev_server(self) -> CommandResult: ...
    async def stop_dev_server(self) -> bool: ...
    def get_state(self) -> SandboxState: ...
