from typing import Protocol, Optional, List


class FileStoragePort(Protocol):
    async def read(self, path: str) -> Optional[str]: ...
    async def write(self, path: str, content: str) -> bool: ...
    async def delete(self, path: str) -> bool: ...
    async def list(self, path: str = "/") -> List[str]: ...
    async def exists(self, path: str) -> bool: ...
